name: point_of_sell
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  http: ^0.13.3
  flutter_bloc: ^7.0.0
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4
  fluttertoast: ^8.0.9
  go_router: ^13.1.0
  flutter_local_notifications: ^16.3.2
  shared_preferences: ^2.0.13
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.7
  firebase_messaging: ^14.7.10
  pdf: ^3.6.5
  printing: ^5.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
