// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjbhk2lu8OklASQgGR_pjIk9nqzUVe2sU',
    appId: '1:938036728260:web:8fcf8e55f302603d819491',
    messagingSenderId: '938036728260',
    projectId: 'point-of-sell---pos',
    authDomain: 'point-of-sell---pos.firebaseapp.com',
    storageBucket: 'point-of-sell---pos.appspot.com',
    measurementId: 'G-HBSY93ZF0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM0rFAgFMpit49dRs0dwL7EUXjWlYInI4',
    appId: '1:938036728260:android:831a808160c6f78e819491',
    messagingSenderId: '938036728260',
    projectId: 'point-of-sell---pos',
    storageBucket: 'point-of-sell---pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNNrcm3FOeLfePm2nKdCWtOI-oCaz_QJo',
    appId: '1:938036728260:ios:101cb2598c0f0bb2819491',
    messagingSenderId: '938036728260',
    projectId: 'point-of-sell---pos',
    storageBucket: 'point-of-sell---pos.appspot.com',
    iosBundleId: 'com.example.pointOfSell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNNrcm3FOeLfePm2nKdCWtOI-oCaz_QJo',
    appId: '1:938036728260:ios:101cb2598c0f0bb2819491',
    messagingSenderId: '938036728260',
    projectId: 'point-of-sell---pos',
    storageBucket: 'point-of-sell---pos.appspot.com',
    iosBundleId: 'com.example.pointOfSell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjbhk2lu8OklASQgGR_pjIk9nqzUVe2sU',
    appId: '1:938036728260:web:a4fae0b1200b893d819491',
    messagingSenderId: '938036728260',
    projectId: 'point-of-sell---pos',
    authDomain: 'point-of-sell---pos.firebaseapp.com',
    storageBucket: 'point-of-sell---pos.appspot.com',
    measurementId: 'G-CHSQWH4TVH',
  );
}
